// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	AddressInfo
	Company
	Employee
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CompanyType int32

const (
	CompanyType_Private   CompanyType = 0
	CompanyType_Public    CompanyType = 1
	CompanyType_NonProfit CompanyType = 2
)

var CompanyType_name = map[int32]string{
	0: "Private",
	1: "Public",
	2: "NonProfit",
}
var CompanyType_value = map[string]int32{
	"Private":   0,
	"Public":    1,
	"NonProfit": 2,
}

func (x CompanyType) String() string {
	return proto1.EnumName(CompanyType_name, int32(x))
}
func (CompanyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddressInfo struct {
	Country string `protobuf:"bytes,5,opt,name=Country" json:"Country,omitempty"`
	City    string `protobuf:"bytes,6,opt,name=City" json:"City,omitempty"`
	Street  string `protobuf:"bytes,7,opt,name=Street" json:"Street,omitempty"`
}

func (m *AddressInfo) Reset()                    { *m = AddressInfo{} }
func (m *AddressInfo) String() string            { return proto1.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()               {}
func (*AddressInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddressInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddressInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddressInfo) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

type Company struct {
	Name      string       `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Employees []*Employee  `protobuf:"bytes,2,rep,name=Employees" json:"Employees,omitempty"`
	Type      CompanyType  `protobuf:"varint,3,opt,name=Type,enum=proto.CompanyType" json:"Type,omitempty"`
	Adress    *AddressInfo `protobuf:"bytes,4,opt,name=Adress" json:"Adress,omitempty"`
}

func (m *Company) Reset()                    { *m = Company{} }
func (m *Company) String() string            { return proto1.CompactTextString(m) }
func (*Company) ProtoMessage()               {}
func (*Company) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Company) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func (m *Company) GetType() CompanyType {
	if m != nil {
		return m.Type
	}
	return CompanyType_Private
}

func (m *Company) GetAdress() *AddressInfo {
	if m != nil {
		return m.Adress
	}
	return nil
}

type Employee struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	SSN  string `protobuf:"bytes,2,opt,name=SSN" json:"SSN,omitempty"`
}

func (m *Employee) Reset()                    { *m = Employee{} }
func (m *Employee) String() string            { return proto1.CompactTextString(m) }
func (*Employee) ProtoMessage()               {}
func (*Employee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetSSN() string {
	if m != nil {
		return m.SSN
	}
	return ""
}

func init() {
	proto1.RegisterType((*AddressInfo)(nil), "proto.AddressInfo")
	proto1.RegisterType((*Company)(nil), "proto.Company")
	proto1.RegisterType((*Employee)(nil), "proto.Employee")
	proto1.RegisterEnum("proto.CompanyType", CompanyType_name, CompanyType_value)
}

func init() { proto1.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0xc1, 0x6a, 0x83, 0x40,
	0x10, 0xed, 0xaa, 0x59, 0xeb, 0x2c, 0x6d, 0x65, 0x0e, 0x65, 0x8f, 0xe2, 0xa1, 0x48, 0xa0, 0xa1,
	0xa4, 0xf4, 0x03, 0x42, 0xe8, 0xa1, 0x17, 0x11, 0xed, 0x0f, 0x98, 0xba, 0x01, 0x21, 0xba, 0xb2,
	0x6e, 0x0a, 0xfe, 0x4d, 0x3f, 0xb5, 0x38, 0xd1, 0xd6, 0x43, 0x4e, 0xfb, 0xe6, 0xcd, 0x9b, 0x7d,
	0xef, 0x01, 0x54, 0xaa, 0xd1, 0x9b, 0xce, 0x68, 0xab, 0x71, 0x45, 0x4f, 0x5c, 0x80, 0xd8, 0x55,
	0x95, 0x51, 0x7d, 0xff, 0xd1, 0x1e, 0x35, 0x4a, 0xf0, 0xf7, 0xfa, 0xdc, 0x5a, 0x33, 0xc8, 0x55,
	0xc4, 0x92, 0x20, 0x9f, 0x47, 0x44, 0xf0, 0xf6, 0xb5, 0x1d, 0x24, 0x27, 0x9a, 0x30, 0x3e, 0x02,
	0x2f, 0xac, 0x51, 0xca, 0x4a, 0x9f, 0xd8, 0x69, 0x8a, 0x7f, 0xd8, 0xf8, 0x4d, 0xd3, 0x95, 0x2d,
	0xdd, 0xa5, 0x65, 0xa3, 0x24, 0xbb, 0xdc, 0x8d, 0x18, 0x9f, 0x21, 0x78, 0x6f, 0xba, 0x93, 0x1e,
	0x94, 0xea, 0xa5, 0x13, 0xb9, 0x89, 0xd8, 0x3e, 0x5c, 0x62, 0x6d, 0x66, 0x3e, 0xff, 0x57, 0xe0,
	0x13, 0x78, 0x9f, 0x43, 0xa7, 0xa4, 0x1b, 0xb1, 0xe4, 0x7e, 0x8b, 0x93, 0x72, 0x32, 0x18, 0x37,
	0x39, 0xed, 0x71, 0x0d, 0x7c, 0x47, 0x55, 0xa4, 0x17, 0xb1, 0x44, 0xfc, 0x29, 0x17, 0x05, 0xf3,
	0x49, 0x11, 0xbf, 0xc0, 0xed, 0x6c, 0x70, 0x35, 0x62, 0x08, 0x6e, 0x51, 0xa4, 0xd2, 0x21, 0x6a,
	0x84, 0xeb, 0x37, 0x10, 0x0b, 0x4b, 0x14, 0xe0, 0x67, 0xa6, 0xfe, 0x2e, 0xad, 0x0a, 0x6f, 0x10,
	0x80, 0x67, 0xe7, 0xc3, 0xa9, 0xfe, 0x0a, 0x19, 0xde, 0x41, 0x90, 0xea, 0x36, 0x33, 0xfa, 0x58,
	0xdb, 0xd0, 0x39, 0x70, 0xca, 0xf0, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x69, 0x0c, 0x0f, 0x0b,
	0x7c, 0x01, 0x00, 0x00,
}
