// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package protobuffer is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Entity
	Data
*/
package protobuffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entity struct {
	Code    int32  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	REF     string `protobuf:"bytes,2,opt,name=REF" json:"REF,omitempty"`
	Display string `protobuf:"bytes,3,opt,name=Display" json:"Display,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entity) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Entity) GetREF() string {
	if m != nil {
		return m.REF
	}
	return ""
}

func (m *Entity) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

type Data struct {
	Entity []*Entity `protobuf:"bytes,1,rep,name=entity" json:"entity,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Data) GetEntity() []*Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "protobuffer.Entity")
	proto.RegisterType((*Data)(nil), "protobuffer.Data")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Merger service

type MergerClient interface {
	Merge(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
}

type mergerClient struct {
	cc *grpc.ClientConn
}

func NewMergerClient(cc *grpc.ClientConn) MergerClient {
	return &mergerClient{cc}
}

func (c *mergerClient) Merge(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := grpc.Invoke(ctx, "/protobuffer.Merger/Merge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Merger service

type MergerServer interface {
	Merge(context.Context, *Data) (*Data, error)
}

func RegisterMergerServer(s *grpc.Server, srv MergerServer) {
	s.RegisterService(&_Merger_serviceDesc, srv)
}

func _Merger_Merge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Merge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuffer.Merger/Merge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Merge(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuffer.Merger",
	HandlerType: (*MergerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Merge",
			Handler:    _Merger_Merge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x06, 0x53, 0x49, 0xa5, 0x69, 0x69, 0xa9, 0x45,
	0x4a, 0x1e, 0x5c, 0x6c, 0xae, 0x79, 0x25, 0x99, 0x25, 0x95, 0x42, 0x42, 0x5c, 0x2c, 0xce, 0xf9,
	0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x90,
	0xab, 0x9b, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0x29, 0x24, 0xc1, 0xc5, 0xee, 0x92,
	0x59, 0x5c, 0x90, 0x93, 0x58, 0x29, 0xc1, 0x0c, 0x16, 0x85, 0x71, 0x95, 0x8c, 0xb9, 0x58, 0x5c,
	0x12, 0x4b, 0x12, 0x85, 0xb4, 0xb9, 0xd8, 0x52, 0xc1, 0x26, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x70,
	0x1b, 0x09, 0xeb, 0x21, 0xd9, 0xa7, 0x07, 0xb1, 0x2c, 0x08, 0xaa, 0xc4, 0xc8, 0x9c, 0x8b, 0xcd,
	0x37, 0xb5, 0x28, 0x3d, 0xb5, 0x48, 0x48, 0x97, 0x8b, 0x15, 0xcc, 0x12, 0x12, 0x44, 0x51, 0x0f,
	0x32, 0x52, 0x0a, 0x53, 0x28, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8f,
	0x05, 0x0d, 0x78, 0xd9, 0x00, 0x00, 0x00,
}
